import { Metadata } from "next";

export const SITE_CONFIG = {
  name: "Labto AI",
  title: "Labto AI — Custom AI Chatbot & Website Copilot",
  description:
    "Transform any website with an autonomous 24/7 AI assistant. Instantly answer visitor questions, crawl knowledge bases, capture leads, recommend products, and embed in 1 minute.",
  url: process.env.NEXT_PUBLIC_APP_URL || "https://labtoai.com",
  ogImage: "/og-image.jpg",
  twitterHandle: "@labto_ai",
  keywords: [
    "Labto AI",
    "AI Chatbot for Ecommerce Website",
    "AI Shopping Assistant",
    "Autonomous Sales Chatbot",
    "AI Customer Service Bot",
    "Shopify AI Chatbot",
    "WooCommerce AI Plugin",
    "WordPress AI Assistant",
    "Next.js AI Chatbot Widget",
    "React AI Assistant",
    "AI Shopping Concierge",
    "E-Commerce AI Copilot",
    "Increase Store Conversion Rate with AI",
    "Automated Product Recommendation Chatbot",
    "AI Sales Agent for Ecommerce",
    "Smart Shopping Assistant Widget",
    "AI Chatbot That Adds Products to Cart",
    "Ecommerce AI Agent 2026",
    "AI Chatbot to Boost Online Sales",
    "Conversational Commerce AI",
    "Shopify AI Shopping Assistant App",
    "Shopify Automated Customer Support Bot",
    "Add AI Chatbot to WordPress Site",
    "Laravel Ecommerce AI Chatbot",
    "Webflow AI Chatbot Widget",
    "Wix AI Chatbot Integration",
    "Magento AI Shopping Assistant",
    "PHP Website AI Chatbot",
    "Svelte Ecommerce AI Assistant",
    "Astro AI Chatbot Widget",
    "HTML Website AI Assistant Embed",
    "Fastest AI Chatbot for Website",
    "Sub-Second Latency AI Chatbot",
    "RAG Chatbot for Ecommerce Catalog",
    "Zero Hallucination AI Assistant",
    "AI Chatbot That Reads Website Pages",
    "Website Crawler AI Chatbot",
    "Custom Knowledge Base AI Chatbot",
    "AI Chatbot Trained on Website Content",
    "Vector Search Chatbot for Online Store",
    "pgvector Ecommerce AI Assistant",
    "Hybrid Search Website AI Bot",
    "AI Chatbot Trained on Product Catalog",
    "LLM Customer Support Agent",
    "Domain Restricted Knowledge AI",
    "White Label Website AI Chatbot Widget",
    "24/7 Automated Customer Support Chatbot",
    "AI Customer Service Software",
    "Replace Human Live Chat with AI",
    "AI Chatbot with Lead Generation",
    "Automated Order Tracking Chatbot",
    "FAQ Answering AI Chatbot",
    "AI Chatbot That Collects Customer Emails",
    "Reduce Support Tickets with AI Chatbot",
    "Instant Response Customer Service Bot",
    "Smart Website Copilot for Visitors",
    "Multilingual AI Chatbot for Website",
    "AI Customer Engagement Tool",
    "Interactive Shopping Concierge Widget",
    "Website Visitor Assistant Bot",
    "AI Virtual Sales Rep",
    "Tidio AI Alternative",
    "Intercom Fin Alternative",
    "Wonderchat Alternative",
    "Chatbase Alternative for Ecommerce",
    "Fastbots Alternative",
    "CustomGPT Alternative for Stores",
    "Botpress Ecommerce Alternative",
    "Voiceflow Website Widget Alternative",
    "Best Ecommerce AI Chatbot 2026",
    "Top Rated AI Assistant for Online Shops",
    "Affordable AI Customer Support Chatbot",
    "No Code AI Chatbot for Website",
    "1-Click Install AI Chatbot",
    "Best Shopping Concierge Platform",
    "AI Live Chat Widget for Websites",
    "AI Chatbot with Instant Cart Sync",
    "Interactive Variant Selector in AI Chat",
    "AI Chatbot with Product Cards",
    "Embeddable Floating AI Chat Widget",
    "Customizable AI Chat Widget Design",
    "AI Chat Widget Clean White Theme",
    "Instant Checkout Redirect AI Assistant",
    "Catalog Crawling AI Chatbot",
    "AI Assistant with Suggestion Chips",
    "Realtime Streaming AI Chatbot Widget",
    "AI Chatbot REST API for Developers",
    "Website Scraping AI Knowledge Base",
    "PDF Upload AI Chatbot Builder",
    "Rate Limiting and Security Guard AI",
    "Turn Website into AI Conversational Assistant",
    "How to Increase Ecommerce Sales with AI",
    "Best AI Tools for Online Store Owners",
    "Best AI Tools for Shopify Store in 2026",
    "Improve Website Conversion Rate with AI",
    "Automate Customer Questions on Website",
    "AI Shopping Assistant for D2C Brands",
    "Boost Store Revenue with Autonomous AI Agent",
    "How to Automate Sales on My Website",
    "AI Customer Copilot for Modern Brands",
    "Automated Ecommerce Shopping Concierge",
    "AI Chatbot for Fashion Clothing Store",
    "AI Shopping Assistant for Beauty and Cosmetics",
    "AI Chatbot for Electronics Website",
    "Dropshipping AI Chatbot Assistant",
    "B2B Ecommerce AI Chatbot",
    "AI Sales Chatbot for Luxury Brands",
    "AI Chatbot for Jewelry Store Website",
    "Automated Shopping Assistant for Furniture Store",
    "AI Chatbot for Fitness and Gym Equipment Store",
    "Food and Grocery Ecommerce AI Chatbot",
    "AI Sales Assistant for Auto Parts Website",
    "Digital Products AI Shopping Assistant",
    "AI Chatbot for Subscription Box Business",
    "AI Customer Support for Wholesale Websites",
    "D2C Brand AI Shopping Concierge",
    "How to Reduce Cart Abandonment with AI Chatbot",
    "AI Chatbot to Recover Abandoned Carts",
    "Increase Checkout Conversion with AI Assistant",
    "AI Chatbot with Exit Intent Popup",
    "Smart Upsell and Cross Sell AI Chatbot",
    "Automated Discount Offering AI Chatbot",
    "AI Chatbot for Flash Sales and Promotions",
    "Personalized Product Finder AI Chatbot",
    "AI Chatbot That Recommends Right Shoe Size",
    "AI Quiz Chatbot for Product Matching",
    "Interactive Product Discovery AI Assistant",
    "AI Chatbot That Increases Average Order Value",
    "Automated Customer Buying Guide AI",
    "AI Chatbot for Personalized Shopping Experience",
    "Instant Sales Closer AI Chatbot for Stores",
    "Multilingual AI Chatbot for International Ecommerce",
    "AI Chatbot That Speaks Spanish and French for Store",
    "AI Shopping Assistant with Currency Conversion",
    "24 7 Night Time Sales Assistant Bot",
    "Automated Customer Support While You Sleep",
    "AI Chatbot That Answers in Customer Language",
    "Global Ecommerce Customer Service Automation",
    "AI Chatbot for Cross Border Ecommerce",
    "Multi Currency AI Shopping Concierge",
    "Instant Response Time Customer Support Bot",
    "Squarespace AI Chatbot Widget",
    "Framer AI Chatbot Integration",
    "Ghost CMS AI Assistant Widget",
    "Prestashop AI Shopping Assistant Module",
    "OpenCart AI Customer Support Extension",
    "Ecwid AI Chatbot Plugin",
    "Bubble io AI Chatbot Integration",
    "FlutterFlow AI Chat Widget Embed",
    "Headless Commerce AI Assistant API",
    "Strapi AI Chatbot Webhook Integration",
    "Sanity CMS Ecommerce AI Copilot",
    "Gatsby Ecommerce AI Chatbot Widget",
    "Remix Run Ecommerce AI Chat Assistant",
    "Nuxt JS Ecommerce AI Chatbot Integration",
    "Zapier AI Chatbot Integration for Ecommerce",
    "AI Chatbot for Live Order Tracking",
    "Where is My Order AI Chatbot Bot",
    "Automated Return and Refund Policy Chatbot",
    "Shipping and Delivery Inquiry AI Assistant",
    "AI Chatbot That Checks Order Status",
    "Automated Warranty Claim AI Assistant",
    "Customer Self Service AI Portal Widget",
    "AI Chatbot for Store Opening Hours and Location",
    "Stock Availability Checker AI Chatbot",
    "Instant Inventory Lookup AI Chatbot",
    "AI Chatbot That Schedules Product Demos",
    "AI Bot for Booking Customer Appointments",
    "Automated Quote Generator AI Chatbot",
    "AI Chatbot with Contact Form Handoff",
    "AI Chatbot That Sends Transcript to Email",
    "Claude 3 5 Sonnet Ecommerce Chatbot",
    "LLaMA 3 3 70B Website Assistant",
    "DeepSeek R1 Website Customer Support Bot",
    "Gemini 2 0 Flash Ecommerce Chat Assistant",
    "Groq Ultra Fast AI Chatbot for Websites",
    "OpenRouter AI Chatbot for Store",
    "Hybrid Dense and Sparse Search Website Chatbot",
    "Semantic Product Search AI Chatbot",
    "Context Aware Website AI Copilot",
    "AI Chatbot with Zero Prompt Injection Vulnerability",
    "GDPR Compliant AI Chatbot for Website",
    "SOC2 Compliant Customer Support AI Bot",
    "Self Hosted Website Knowledge Base AI",
    "Privacy Focused Website AI Assistant",
    "AI Chatbot That Respects Visitor Cookies",
    "Free Trial AI Chatbot for Website",
    "Cheapest AI Customer Support Chatbot",
    "AI Chatbot Pricing for Ecommerce Stores",
    "Pay As You Go Website AI Chatbot",
    "White Label AI Chatbot for Marketing Agencies",
    "Resell AI Chatbot to Web Design Clients",
    "Agency Client Portal AI Chatbot Builder",
    "How Much Does an Ecommerce AI Chatbot Cost",
    "Save Money on Customer Support Agents with AI",
    "ROI of AI Shopping Assistant for Stores",
    "Top 10 AI Chatbots for Online Stores 2026",
    "Best Customer Service AI Tools for Startups",
    "Scalable AI Chatbot for High Traffic Ecommerce",
    "Fastest Loading AI Chat Widget Script",
    "Lightweight AI Chat Widget No Lag",
  ],
  author: "Labto AI",
  creator: "Labto AI",
};

export function constructMetadata({
  title = SITE_CONFIG.title,
  description = SITE_CONFIG.description,
  image = SITE_CONFIG.ogImage,
  canonicalUrl,
  noIndex = false,
  keywords = SITE_CONFIG.keywords,
}: {
  title?: string;
  description?: string;
  image?: string;
  canonicalUrl?: string;
  noIndex?: boolean;
  keywords?: string[];
} = {}): Metadata {
  const finalTitle = title.includes("Labto AI") ? title : `${title} | Labto AI`;
  const url = canonicalUrl
    ? `${SITE_CONFIG.url}${canonicalUrl.startsWith("/") ? canonicalUrl : `/${canonicalUrl}`}`
    : SITE_CONFIG.url;

  return {
    title: finalTitle,
    description,
    keywords,
    authors: [{ name: SITE_CONFIG.author, url: SITE_CONFIG.url }],
    creator: SITE_CONFIG.creator,
    metadataBase: new URL(SITE_CONFIG.url),
    alternates: {
      canonical: url,
    },
    openGraph: {
      title: finalTitle,
      description,
      url,
      siteName: SITE_CONFIG.name,
      images: [
        {
          url: image,
          width: 1200,
          height: 630,
          alt: `${SITE_CONFIG.name} — Autonomous AI Assistant`,
        },
      ],
      locale: "en_US",
      type: "website",
    },
    twitter: {
      card: "summary_large_image",
      title: finalTitle,
      description,
      images: [image],
      creator: SITE_CONFIG.twitterHandle,
    },
    robots: {
      index: !noIndex,
      follow: !noIndex,
      googleBot: {
        index: !noIndex,
        follow: !noIndex,
        "max-video-preview": -1,
        "max-image-preview": "large",
        "max-snippet": -1,
      },
    },
    icons: {
      icon: [
        { url: "/icon.svg", type: "image/svg+xml" },
        { url: "/favicon.ico", sizes: "48x48" },
      ],
      shortcut: ["/icon.svg"],
      apple: [{ url: "/icon.svg" }],
    },
  };
}

export function generateSoftwareSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "SoftwareApplication",
    name: "Labto AI",
    applicationCategory: "BusinessApplication",
    operatingSystem:
      "Web-based, Cloud, Shopify, WooCommerce, WordPress, Webflow, Next.js, Custom Websites",
    offers: {
      "@type": "AggregateOffer",
      priceCurrency: "USD",
      lowPrice: "0",
      highPrice: "349",
      offerCount: "5",
    },
    description: SITE_CONFIG.description,
    url: SITE_CONFIG.url,
    publisher: {
      "@type": "Organization",
      name: "Labto AI",
      url: SITE_CONFIG.url,
      logo: `${SITE_CONFIG.url}/og-image.jpg`,
    },
  };
}

export function generateOrganizationSchema() {
  return {
    "@context": "https://schema.org",
    "@type": "Organization",
    name: "Labto AI",
    url: SITE_CONFIG.url,
    logo: `${SITE_CONFIG.url}/og-image.jpg`,
    sameAs: [
      "https://twitter.com/labto_ai",
      "https://github.com/moshiurrahmandeap11",
    ],
    contactPoint: {
      "@type": "ContactPoint",
      contactType: "customer support",
      email: "support@labtoai.com",
      availableLanguage: ["English"],
    },
  };
}
